### PR TITLE
Upgraded to work with ZeroMQ 3.2.0, SBT 0.12.0, Scala 2.10.0-M7

### PR DESCRIPTION
**Pull request by helena**
Let me know what you think, there is a lot of test coverage needed still, I can try to pick away at it over the next few months.
- Tested against 2.2.0 and 3.2.0 on MacOSX
- See Changes.md for full list of additions, removals, modifications
- Added scalariform plugin
- Added sbt-run test duration output
- Removed build.sbt and replaced it with project/Build.scala
- Removed the sbt plugin - that should live in the developer's env vs the codebase
- Removed sbt build file (see above)
- Upgraded jnr
- Upgraded jna
- Fixed a few socket option set/get version calls
- Much more test coverage is needed, as is testing on other operating systems

### CODE REVIEW

**Comment by jvirtanen** [comment]
Phew, there's a lot going on! :smiley:

@helena, could you try to split the big commit into smaller commits (along the list in the pull request text)? That would make it a lot easier to go through all the changes.

**Comment by helena** [comment]
Hi, I can in the future but that's how we do it for akka commits - a squash into one. I'll break them up for future commits :-)

**Comment by helena** [comment]
I am going through all the set/get socket ops and do notice discrepancies between versions you check and the versions the docs show as being included in the api, for example set receive timeout was available for 2.2.0. So I am migrating those (another branch). I am confirming this against the java binding as well.

**Comment by helena** [comment]
Actually I just went through the version logic for all socket opt set/get and I had an inconsistency which is now fixed. Reviewed the versioning in scala binding, java binding and documentation for 3.2, 2.2 to fix things. So I will have to push these changes to this branch. Now everything looks correct but there were issues in the previous scala binding that I've now fixed :)

**Comment by alexandreagular** [comment]
Hi,

I cloned your branch to see what you did, the unit tests are not passing.

I have opened a pull request a couple of weeks ago where I did similar changes to you. Could you check it, I think there is no need to have both.

**Comment by penberg** [comment]
AFAICT, this is no longer needed with latest master. I'm closing the pull request.

**Pull request closed without merging**
